services:
  # MySQL データベース
  db:
    image: mysql:8.0
    container_name: gachimatsu-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gachimatsu
      MYSQL_USER: gachimatsu_user
      MYSQL_PASSWORD: gachimatsu_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/sql:/docker-entrypoint-initdb.d
    networks:
      - gachimatsu-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # バックエンド API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gachimatsu-backend
    restart: unless-stopped
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: gachimatsu
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gachimatsu-network

# データ永続化用のボリューム
volumes:
  mysql_data:

# ネットワーク設定
networks:
  gachimatsu-network:
    driver: bridge